### ISSUE TITLE
List external resources

### ISSUE THREAD

**Issue by bebraw** [survivejs/webpack_react#144]
I have to figure out a good way to do this. There are tons of resources and I fear spamming the text with these wouldn't be a nice move. Perhaps an appendix would work. Even tools could be pushed there.

**Comment by Cryptolemming** [comment]
Hi,

sorry just noticed your comments on the previous issue.  My github watching is now in effect :)

Will take a look at the changes soon and give the tutorial another go - have more Flux experience now as well.

About this issue - maybe a medium.com style small, collapsible annotation / indicator beside the area which warrants an external resource?  

For the print version - simple footer should do?

**Comment by bebraw** [comment]
I don't have a lot of power over formatting. We're pretty much stuck with [Leanpub formatting options](https://leanpub.com/help/manual).

What if we did a separate resource page on the site? That would allow us to provide better ux and get something that's easier to keep up to date.

The problem is that if we do a print version at some point, the reference is going to get old really fast.

**Comment by Cryptolemming** [comment]
Oh okay didn't know about the Leanpub limitations.

Resource page sounds good with some indication to look at the relevant resource link in the web version.

Yeah good point about the print version.  Although there are resources which just explain things in a way that can stand the test of time.  More generic information about how Webpack works as included earlier for example.  A concise article or presentation about Flux architecture etc.

examples:
[1](http://blog.mgechev.com/2015/05/15/flux-in-depth-overview-components/) (spelling and grammar mistakes but explanations are very good)
[2](https://www.youtube.com/watch?v=Bic_sFiaNDI) (excellent video for Flux foundations)

Otherwise I suppose trying to be as exhaustive in the material while nurturing simplicity and efficiency best you can do there.

**Comment by bebraw** [comment]
What if we set up a separate repo for this and pulled resources from there to the online version? That way we get something that's easy to contribute to (stays up to date better I think).

There could be a convention like this:

**01_webpack_compared.md**

```markdown
* [Demo resource](http://...)
```

At site it would look roughly like this:

```markdown
## Conclusion

You should understand how to set up React with webpack now...

## Extra Resources

* [Demo resource](http://...)

...
```

This is simple for me to set up and could be a nice way to make the site more useful while allowing people to contribute.

**Comment by bebraw** [comment]
I implemented a little sidebar thinger just for this. Only the styling chapter contains some for now. The plan is to make it easy to contribute these (separate repo).
