### ISSUE TITLE
Implementing a Basic Note Application -

### ISSUE THREAD

**Issue by davegomez** [survivejs/webpack_react#237]
When I get to this line *"If you hit the button a few times now, you should see new items. It might not be pretty yet, but it works."* I had to execute `npm start` again for the `bind` to `this` takes effect, otherwise throws and error saying can't `setState` of `undefined`

**Comment by bebraw** [comment]
Yeah, the problem is that HMR doesn't pick up changes made to `constructor` since it just replaces code. I recall the next edition should have a warning about this but I'll check to be sure.

No need to restart the server btw. Just a refresh at the browser should be enough.

It would be nice to find a HMR compatible solution for this particular problem. I feel React 0.14 might help a little on that regard as it allows us to write simple components as pure functions.

**Comment by bebraw** [comment]
There's a warning in the book now. Hopefully we can get rid of those `constructor` bits somehow to mitigate this altogether.

Thanks for the report!

**Comment by af7** [comment]
Where in the code is this problem?

**Comment by bebraw** [comment]
@af7 Basically you'll bump into this any time you tweak a component constructor. I have a hunch we might find something better in the future but we'll see.
