### ISSUE TITLE
Implementing a Basic Note Application -

### ISSUE THREAD

**Issue by ateev** [survivejs/webpack_react#275]
In the section `Connecting addNote with Data Model` can you please explain why you used `this.addNote = this.addNote.bind(this);`

I'm new to ES6 so maybe its a noob question. Please explain how this works. Also can this be written more easily ?

Thanks.

**Comment by bebraw** [comment]
This is due to `this.setState`. If we don't bind the method to the instance itself, that won't make anything useful. An alternative way would be to bind it when it's invoked. Then you would get something like `() => this.addNote` or `this.addNote.bind(this)` at `render()`. This would eat a little bit of performance while being almost as verbose. I feel dealing with the bindings at the constructor is neatest.

In the future we might get [property initializers](https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#autobinding) to deal with this. Then you could write `addNote = () => {`. I am not using that yet given it's still so early in the standardization process and might change.

I agree the current way is far from ideal and I would love to eliminate it altogether. For now we have to go with this, though... I'll make sure to clarify the part where it's first used. Thanks for bringing this up.

**Comment by ateev** [comment]
Thanks for the explanation. Now i got it. When you have many components on a page getting invoked, it becomes pretty verbose and performance eater. This will avoid that.
