### ISSUE TITLE
Developing with Webpack -

### ISSUE THREAD

**Issue by nngrey** [survivejs/webpack_react#281]
I am working my way through your tutorial again and will provide some suggestions as I go along. Just so you understand my perspective, I am a junior developer working mostly with Rails but also some React. 

1. "You can serve /build through a dummy server such as serve (npm i serve -g). Examine the results in a browser." I was not sure what "examine the results in the browser" meant here. I thought 'npm i serve -g' might have launched a server at 3000 or 8080, but it did not seem to, so I simply navigated to the file in my repo.

2. The following code in webpack.config.js seems to disappear immediately after it is introduced. It then reappears with a conditional toward the end of the chapter:

  devServer: {
    historyApiFallback: true,
    hot: true,
    inline: true,
    progress: true,

    // parse host and port from env so this is easy
    // to customize
    host: process.env.HOST,
    port: process.env.PORT
  },

You might want to be more explicit if you intend for the code to be removed.

3. The webpack-dev-server has to be restarted at several points during the chapter; however we have never stopped it, so hitting 'npm start' does not do anything. You may want to have people run 'npm restart' or ctrl-c and npm start.

**Comment by bebraw** [comment]
Thanks a lot for the feedback. This is very valuable!

> The webpack-dev-server has to be restarted at several points during the chapter; however we have never stopped it, so hitting 'npm start' does not do anything. You may want to have people run 'npm restart' or ctrl-c and npm start.

Note that it's enough to hit refresh at the browser. No need to restart the server.

The problem is that as the tooling just patches methods. If there are bound methods (`.bind` at constructor), those references won't get updated. The situation might change in the future but at the moment it's a little problematic. One "solution" would be to push the bound methods as functions inside `render` but I feel that's stylistically weak choice.

I'll add a big warning about this and get those other issues resolved. Thanks again!

**Comment by bebraw** [comment]
I made tweaks related to the issues you pointed at out to the [dev branch](https://github.com/survivejs/webpack_react/tree/dev). Feel free to comment there. New issues are very welcome as well. :+1:

I have to dig through all of the code examples one of these days (#224).
