### ISSUE TITLE
Building Kanban -

### ISSUE THREAD

**Issue by nngrey** [survivejs/webpack_react#288]
Been away a couple weeks and came back to do 'Building Kanban.' I think you have updated the code in webpack.config.js because my code seemed out of date. I had to overwrite my file with code from source and then everything seemed okay.

It took me a minute to figure out this instruction:

You should find it at https://<name>.github.io/<project> assuming it worked.
"
You might consider adding an explanatory line like "- where <name> is your github username and <project> is the name of your github repository for this project. 

Also, a friend and I have worked through the project and now we want to modify it for another purpose - a public health logic model app. We want to add user accounts, authentication, and persistence so that users can create and save many logic models in their accounts. Do you have any suggestions for us? Before we came across your tutorial, we were considering creating a rails app with a react front end that used ajax calls from the flux stores to retrieve data from the backend. It would be nice if we could modify the current app from the tutorial, instead of starting over. Please let me know if you have any thoughts. 

By the way, I am going to purchase the book to support your work. This has been a great experience overall. Thanks!

**Comment by bebraw** [comment]
> Been away a couple weeks and came back to do 'Building Kanban.' I think you have updated the code in webpack.config.js because my code seemed out of date. I had to overwrite my file with code from source and then everything seemed okay.

Yeah. There have been quite a few changes. I try to keep up with the world. :+1:

Please note that you can find release notes at [the blog](http://survivejs.com/blog/). I go through major changes there.

> You should find it at https://.github.io/ assuming it worked. ...

Thanks. I fixed this at the `dev` branch. It will go out in the next release.

> Also, a friend and I have worked through the project and now we want to modify it for another purpose - a public health logic model app. We want to add user accounts, authentication, and persistence so that users can create and save many logic models in their accounts. Do you have any suggestions for us? Before we came across your tutorial, we were considering creating a rails app with a react front end that used ajax calls from the flux stores to retrieve data from the backend. It would be nice if we could modify the current app from the tutorial, instead of starting over. Please let me know if you have any thoughts.

I have codified the ideas of the book into a little [boilerplate](https://github.com/survivejs/react-component-boilerplate). I've tried to keep it quite light and it's at its best for component development. Perhaps that could work as a starting point.

Personally I prefer to start from a simple boilerplate and add features rather than start with an elaborate one and alter it to suit my purposes. More often than not there's something you disagree with and then you end up fighting with the boilerplate instead of going forward. That said, examining boilerplates can give you ideas on how to resolve certain things.

You will have to think about auth etc. based on the data architecture you choose. They all have their own solutions. I see no reason why a Rails backend couldn't work.

> By the way, I am going to purchase the book to support your work. This has been a great experience overall. Thanks!

Great to hear. The commercial version has some extra goodies in it. ;)

**Comment by bebraw** [comment]
Closing. Feel free to comment here or poke me directly if you have any further issues on your mind.
