### ISSUE TITLE
Discuss how to deploy the Kanban app into production

### ISSUE THREAD

**Issue by bebraw** [survivejs/webpack_react#29]
Related to chapter 11. Need to show whole pipeline and how things go together.

**Comment by justjacksonn** [comment]
This would be fantastic. Most examples/talks focus on the dev side of things, but actually seeing how a QA, Stage and production setup would work with NodeJS, ReactJS and so forth would be very helpful. Myself being a Java/JEE developer, I am familiar with setting up JEE servers for production, scalability, and deploying to them (rolling restart, auto-restart, etc). I am unfamiliar with how you take a nodejs/reactjs application "folder" with build/ lib/ app/ and so forth, bundle it up for deployment, then deploy it.. and what happens when you have multiple servers behind a load balancer.. how to manage state (I assume being rest API driven, there is no state to worry about..thus my issue #31), how to upgrade a server that is already being used (rolling restart or does it happen so fast users wouldn't notice). Things like that would be great to understand.

**Comment by bebraw** [comment]
[Building Kanban](http://survivejs.com/webpack_react/building_kanban/) is likely the best I can do within the current scope. The chapter shows you how to get a respectable production level bundle out of Webpack. It also touches the concept of isomorphism.

I feel discussing load balancers and such would go way out of scope. I also lack the expertise so that doesn't improve things either. :)

It's likely there are other, more deployment specific books, that deal with the topic way better than I ever could.
