### ISSUE TITLE
Chapter 4's use of 'state' in App vs 'state' in Notes/Note

### ISSUE THREAD

**Issue by saschwarz** [survivejs/webpack_react#306]
I'm early in your book, and new to React, so I could have this wrong...! 

I'm wondering if the use of 'state' in App to hold the data model is undesirable and ultimately confusing to new readers? From other React/Flux smart/dumb component reading I've done, I'd propose you make the case for component state *only* holding presentation state and never holding data store/application state. Would it be helpful to make that distinction when you first introduce props/state?

Another thought; I assume when you introduce Alt later on you'll pull the task list/state out of App and provide the task state data to App via App's props? If so, why not start out modeling App that way?

**Comment by bebraw** [comment]
Hi,

Thanks for asking. The point of the current approach is to show what problem data architecture solves. By jumping straight to something more complete, you might miss the distinction. Not all apps even end up needing it if they are very simple. It would be just extra work for little to gain.

The way I see it is that it makes more sense to evolve the application as you go rather than be too prescriptive from the start. This is true in particular if you are doing something new and are still figuring out the right structures and approaches to use.

The point of Flux and such is to take control over application state indeed. UI state should remain on component level. `Editable` is one example of this as you will see.

I agree this could be made more explicit and I'll give it some thought. Perhaps the intro could explain the approach in more detail.

**Comment by saschwarz** [comment]
Thanks for the explanation. Funny when learning I want to try to learn all the "best practices" and try to apply them immediately even on toy problems. Usually they aren't too burdensome and then they become second nature when I work on a more complex application.

**Comment by bebraw** [comment]
Yeah, once you have tried a couple of libs that solve the data management problem, you start to see common patterns.

You can find some alternative implementations of the app below this org if you want to compare at some point. I feel the "dumb" portion of your application shouldn't change if you alter your data architecture. The connection points are somewhere higher in the hierarchy.
