### ISSUE TITLE
Avoidable use of waitFor in Chapter 5?

### ISSUE THREAD

**Issue by ghilios** [survivejs/webpack_react#315]
LaneActions.attachToLane does a waitFor on NoteStore and uses the last note in the array as what was newly created. This seems like a race condition waiting to happen. Could you instead return the newly created note in NoteStore.create, and pass its id into LaneStore.attachToLane? You'd avoid the waitFor (which is already awkward) and avoid some coupling while you're at it

**Comment by bebraw** [comment]
I agree this is problematic. That `waitFor` solution is pretty much forced here as there's a dependency below the surface and we are forced to trust the dispatcher. I don't like it at all, but as far as I understand, there's no way around it in this case.

Interestingly the [redux based implementation](https://github.com/survivejs/redux-demo) skips this problem altogether. There actions are synchronous (not async like here). There we can do things like:

```javascript
  addNote(laneId) {
    const o = this.props.createNote({
      task: 'New task'
    });
    this.props.attachToLane(laneId, o.note.id);
  }
```

[mobservable implementation](https://github.com/survivejs/mobservable-demo) is interesting as well especially because it simplifies reference handling so much.

If there's a way to get rid of `waitFor` while using Alt, I'm all in. So let's leave this open for now.

**Comment by ghilios** [comment]
What's wrong with the following? It seems to work for me - or am I getting lucky?

NoteStore.js
`	create(note) {
		const notes = this.notes;
		note.id = uuid.v4();
		this.setState({
			notes: notes.concat(note)
		});
		return note;
	}`

Lane.jsx
`	addNote(laneId) {
		const note = NoteActions.create({task: 'New task'});
		LaneActions.attachToLane({noteId: note.id, laneId: laneId});
	}`

**Comment by bebraw** [comment]
@ghilios Yeah, that's good. Thanks!

I could swear I tried something like that early on. Maybe something changed in Alt. In any case, that's far better as it avoids some complexity. :+1:
