### ISSUE TITLE
Feedback: Explain why storage in Flux should be singleton

### ISSUE THREAD

**Issue by ghilios** [survivejs/webpack_react#316]
At the end of Chapter 5 you mentioned that creating a NoteStore per Notes dynamically would simplify dealing with relations but... "is a Flex anti-pattern better avoided."

My feedback: Explain and defend this. Alternatively, is there a link somewhere explaining why this is an anti-pattern? One thought that comes to my mind is that it enables deduplication of identical instances and sharing of references. If that's the case, you could probably do it by having a per-Notes NotesReferencesStore that itself handles the nuances of references to a singleton NotesStore.

Thanks!

**Comment by bebraw** [comment]
I instantiated the note stores per each `Notes` container in my early implementations. That's just something I did by intuition. Even though this is a fairly streamlined way to deal with it, there were two big problems:

* You need to deal with store lifecycle as `Notes` get created/removed. Creating isn't a problem. Alt simply didn't/doesn't provide means to deal with latter. I discussed through this with the author and it's by design.
* I recall drag and drop became kind of interesting. It's a hard problem no matter what, though.

You can see a trend towards a single source of truth with solutions like [Redux](http://rackt.org/redux/).

It's possible the current solution isn't ideal and there's some neater way to deal with references. I'm not a big fan of having to do all the reference checking by hand. It's too easy to make mistakes there. You can actually see something similar at Redux based applications in their reducers. Maybe something appears to fill this niche. Currently reference handling is one of those aspects that's not exactly smooth.

**Comment by ghilios** [comment]
Interesting, thanks for that information. I think it would be hugely valuable to include this somewhere in the text, as the path to your solution is also valuable learning!

Redux is next on my list to tackle. I'm really curious to see how it would look there

**Comment by bebraw** [comment]
I'll add something there. Thanks for bringing this up.
