### ISSUE TITLE
From Notes to Kanban -

### ISSUE THREAD

**Issue by lightwave** [survivejs/webpack_react#336]
In http://survivejs.com/webpack_react/from_notes_to_kanban/, I found the following two problems.

1. In NoteStore.js, the get method can't be exported. If you try to export get, it'd cause Chrome to print out a message later in Lane.jsx that no get method for NoteStore. I have to rename it to getNotesByIds

2. The get/getNotesByIds method can be implemented as following, which I find less convoluted.

```es6
getNotesByIds(ids) {
    const idSet = new Set(ids);  // ES6 Set
    return this.notes.filter(note => idSet.has(note.id));
}
```

**Comment by bebraw** [comment]
> In NoteStore.js, the get method can't be exported. If you try to export get, it'd cause Chrome to print out a message later in Lane.jsx that no get method for NoteStore. I have to rename it to getNotesByIds

There's Alt specific bit to deal with this at the constructor:

```javascript
    this.exportPublicMethods({
      get: this.get.bind(this)
    });
```

It's possible I'm missing something obvious here.

One option would be to drop the Alt specific bit and just push the logic to a function and handle it there.

> The get/getNotesByIds method can be implemented as following, which I find less convoluted.

I actually tried something simplified. There's one major constraint. Lane notes need to retain their order. If we didn't have to care about that, the `Set` based implementation would be an excellent alternative.

In order to make it easier to follow the logic of the method, I've annotated it in the `dev` version.

Thanks for the feedback! :+1:

**Comment by bebraw** [comment]
These should be resolved now. Closing.
