### ISSUE TITLE
 Analyzing-Build-Statistics Section - stats.json file cannot be read by webpack analyse

### ISSUE THREAD

**Issue by maxehnert** [survivejs/webpack_react#338]
At this section [analyzing-build-statistics](http://survivejs.com/webpack_react/building_kanban/#analyzing-build-statistics) we write a script to create the `stats.json` file which can be visualized by [webpack](http://webpack.github.io/analyse/). However the first line of the file is not json[1], therefore the analyse tool won't work without deleting that line. 

I couldn't figure out where this line was being written (perhaps you do and there is a better solution) so I modified the stats script to write to a temporary file, then strip out the first line and write to the `stats.json` file and remove the temporary file. (From what I can gather, you have to write to a temporary file to do this programatically)

It's quite a bit more verbose than what currently exists and would likely need more explaination as to what is going on and why, but if you want to make this change, I can do a PR and write it up.

Here is the line that I ended up with:
`    "stats": "webpack --profile --json > tempStats.json && tail -n +2 tempStats.json > stats.json && rm tempStats.json"
`

[1] This is what the first line contains: `clean-webpack-plugin: /pathToMyProject/build has been removed.`

**Comment by bebraw** [comment]
I've addressed this at https://github.com/survivejs/webpack_react/commit/4b02b4b9f285505035acfcd4a6a11f3fadf26508 and https://github.com/survivejs/webpack_react/commit/e3cbc8db956113bc799152b7ed0ad931c7991e9b . The problem is that `CleanPlugin` uses a verbose mode by default. That's why we get that extra output. I have disabled the verbose mode at `dev`.

It feels like it would be far better to solve this at Webpack level, though.

Related issues: https://github.com/webpack/webpack/issues/1904, https://github.com/johnagan/clean-webpack-plugin/issues/11 .
