### ISSUE TITLE
use ES6 static method syntax 

### ISSUE THREAD

**Issue by deepak** [survivejs/webpack_react#386]
can use ES6 static method syntax in [4.8 Understanding React Components](https://github.com/survivejs/webpack_react/blob/08708baba4dfe8908b20688cd39b26bc2d7621dd/manuscript/04_implementing_notes.md#understanding-react-components)

> * `statics` - `statics` contains static properties and method for a component

code sample there can be changed to use `ES6 static method`

```javascript
class Note {
  render() {
    ...
  }

  static willTransitionTo() { 
    ....
  }
}

export default Note;
```

also need to add a section on `static` methods to `language_features`
it does have a section on [class-properties-and-property-initializers](https://github.com/survivejs/webpack_react/blob/08708baba4dfe8908b20688cd39b26bc2d7621dd/manuscript/15_language_features.md#class-properties-and-property-initializers)

**Comment by bebraw** [comment]
That's a good point. I could definitely mention about it there. Thanks. 👍 

There's actually a gotcha related to statics. If you wrap your classes (`connect`, etc.), you can get interesting behavior since they won't be visible outside anymore (hidden behind the wrapper). That would be worth documenting too.

**Comment by deepak** [comment]
found an [issue](https://github.com/acdlite/flummox/issues/173) about static methods. people are discussing some solutions there
