### ISSUE TITLE
Customizing ESlint

### ISSUE THREAD

**Issue by P58603649** [survivejs/webpack_react#43]
This section doesn't make much sense to me - how where do these customisations get applied?

**Comment by bebraw** [comment]
Good point! I'll clarify that.

The idea is that sometimes you specifically **don't** want to lint for a reason or another. ESLint will respect these hints during processing so you don't get errors/warnings. I'll have to think of a concrete example to illustrate this better.

It's a niche use case but something that's good to be aware of since you might run into it sooner or later.

**Comment by gilesbradshaw** [comment]
great (P58603649 was me btw - accidently commented from different account!)
